import { useEffect,useRef,useState } from 'react';
import { ArrowRight,Check,Mic,MonitorUp,MousePointerClick } from 'lucide-react';
import { api } from '../lib/api';
import { SetupSaver,type SetupProfile } from '../lib/personal-setup';
import { SetupChecks } from './SetupChecks';
import './welcome.css';import './personal-setup.css';
const KEY='shuacrew.welcome';export const welcomed=()=>{try{return localStorage.getItem(KEY)==='3';}catch{return false;}};
export function resetWelcome(){try{localStorage.removeItem(KEY);localStorage.removeItem(LATER);}catch{}}
// "Later" means later: setup stays out of the way for three days instead of returning on every launch.
const LATER='shuacrew.setup.later',SNOOZE=3*24*3600_000;
export const setupSnoozed=(now=Date.now())=>{try{return now-Number(localStorage.getItem(LATER)??0)<SNOOZE;}catch{return false;}};
const snooze=()=>{try{localStorage.setItem(LATER,String(Date.now()));}catch{}};
type Native={postMessage(m:unknown):void};const native=()=>(window as unknown as {webkit?:{messageHandlers?:{shuacrew?:Native}}}).webkit?.messageHandlers?.shuacrew;
const steps=['Outcomes','Models','Mac & tools','Voice & control','Work defaults','First outcome'];
interface Runtime{id:string;label:string;status:{installed:boolean;signedIn:boolean|null}}
export function Welcome({onDone}:{onDone:()=>void}){
 const [profile,setProfile]=useState<SetupProfile|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loadAttempt,reload]=useState(0);
 const [runtimes,setRuntimes]=useState<Runtime[]>([]),[runtimeError,setRuntimeError]=useState(''),[perms,setPerms]=useState<{screen?:boolean;hands?:boolean;mic?:boolean}>({});
 const [defaults,setDefaults]=useState<{caps?:{maxMinutes:number|null;maxTokens:number|null};quietHours?:{enabled:boolean}}|null>(null);
 const saver=useRef(new SetupSaver((url,body)=>api(url,{body}))).current;
 useEffect(()=>{let alive=true;setError('');void Promise.all([api<SetupProfile>('/api/personal-setup'),api<{profile?:{goal?:string}}>('/api/learning').catch(()=>null)]).then(([p,l])=>{if(alive)setProfile({...p,goal:p.revision===0?(l?.profile?.goal??''):p.goal});}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[loadAttempt]);
 useEffect(()=>{let alive=true;void api<Runtime[]>('/api/runtimes').then(r=>alive&&setRuntimes(r)).catch(e=>alive&&setRuntimeError(e.message));void api<typeof defaults>('/api/settings').then(r=>alive&&setDefaults(r)).catch(()=>{});return()=>{alive=false;};},[loadAttempt]);
 useEffect(()=>{const screen=(e:Event)=>setPerms(p=>({...p,screen:(e as CustomEvent).detail.granted===true}));const hands=(e:Event)=>setPerms(p=>({...p,hands:(e as CustomEvent).detail.trusted===true}));const poll=()=>{native()?.postMessage({type:'buddyScreenAccess'});native()?.postMessage({type:'buddyHands'});};window.addEventListener('shuacrew:screenAccess',screen);window.addEventListener('shuacrew:hands',hands);window.addEventListener('focus',poll);poll();return()=>{window.removeEventListener('shuacrew:screenAccess',screen);window.removeEventListener('shuacrew:hands',hands);window.removeEventListener('focus',poll);};},[]);
 const change=(patch:Partial<SetupProfile>)=>setProfile(p=>p?{...p,...patch}:p);
 async function save(step:number,complete=false,destination?:string,close=false){if(!profile||saver.busy)return;setBusy(true);setError('');try{const p=await saver.save(profile,{goal:profile.goal,incomePath:profile.incomePath,weeklyHours:profile.weeklyHours,step,complete});setProfile(p);if(close)onDone();if(complete){localStorage.setItem(KEY,'3');onDone();if(destination)window.location.assign(destination);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function mic(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());setPerms(p=>({...p,mic:true}));}catch(e){setPerms(p=>({...p,mic:false}));setError((e as Error).message);}}
 const step=profile?.step??0;
 return <div className="wel personal-setup" role="dialog" aria-modal="true" aria-label="Set up your Shua"><div className="wel-card"><header className="setup-header"><span>SHUA / YOUR PERSONAL WORKSPACE</span><button onClick={()=>{snooze();if(profile)void save(step,false,undefined,true);else onDone();}} disabled={busy} aria-label="Close setup and continue later">Later</button></header><nav className="wel-steps" aria-label="Setup steps">{steps.map((label,i)=><button key={label} disabled={busy||!profile} className={i===step?'is-on':''} aria-current={i===step?'step':undefined} onClick={()=>void save(i)}><i>{i+1}</i>{label}</button>)}</nav>
 <fieldset disabled={busy} className="wel-body">{!profile?<><h1>Make Shua yours.</h1><p>{error?'Your saved data is intact. Resolve the error, then retry.':'Loading your saved setup…'}</p></>:<>
 {step===0&&<><h1>Learn. Build. Make it useful.</h1><p>One connected workspace for your skills, software products, and automation services.</p><label className="setup-field">Your learning or career goal<input autoFocus value={profile.goal} maxLength={500} onChange={e=>change({goal:e.target.value})} placeholder="What do you want to become capable of?"/></label><div className="setup-paths" role="group" aria-label="Income direction">{(['products','services','both'] as const).map(p=><button key={p} aria-pressed={profile.incomePath===p} onClick={()=>change({incomePath:p})}><strong>{p==='products'?'Software products':p==='services'?'Automation services':'Both paths'}</strong><small>{p==='both'?'Research both; test a focused idea in each.':p==='products'?'Build and sell a useful tool.':'Deliver a repeatable solution for clients.'}</small></button>)}</div><label className="setup-field">Hours available each week<input type="number" min={0} max={168} step={0.5} value={profile.weeklyHours??''} onChange={e=>change({weeklyHours:e.target.value===''?null:Number(e.target.value)})} placeholder="Not set"/></label><small>This sets your planning direction. It does not launch work or authorize spending.</small></>}
 {step===1&&<><h1>The right models for each job.</h1><p>The notch and personal assistant use Codex. Crew agents can use your connected Claude and Codex models.</p><div className="wel-list">{runtimes.map(r=><div className="wel-item" key={r.id}><div><b>{r.label}</b><small>{!r.status.installed?'Not installed':r.status.signedIn===true?'Signed in — task execution still needs testing':r.status.signedIn===false?'Signed out':'Authentication not verified'}</small></div></div>)}</div>{runtimeError&&<p role="alert">{runtimeError}</p>}<SetupChecks/><a href="/settings#agents">Manage model connections ↗</a></>}
 {step===2&&<><h1>Give Shua the access you need.</h1><p>Each permission is separate. Choose what to enable; a grant is not a completed action test.</p><div className="wel-list"><Perm icon={Mic} title="Microphone" why="Classic transcription runs locally. Live voice sends audio to OpenAI." on={perms.mic} onAsk={()=>void mic()}/><Perm icon={MonitorUp} title="Screen" why="Observe permitted screen context while you ask or demonstrate." on={perms.screen} onAsk={()=>native()?.postMessage({type:'buddyScreenAccess',ask:true})}/><Perm icon={MousePointerClick} title="Click and type" why="Find controls and execute verified steps. Escape stops replay." on={perms.hands} onAsk={()=>native()?.postMessage({type:'buddyHands',ask:true})}/></div><a href="/integrations">Review tools and MCP connections ↗</a><p className="setup-note">Day-job folders remain excluded. Shua can use connected memory and permitted context; it cannot know unobserved changes.</p></>}
 {step===3&&<><h1>Try it on your Mac.</h1><p>Use “Later” to run these checks, then resume setup. Your saved progress remains here.</p><SetupChecks devices/><a href="/settings#voice">Choose and test your voice mode ↗</a></>}
 {step===4&&<><h1>Work with clear limits.</h1><p>Use your actual settings. New spending, publishing, and messages need their own authorization.</p><dl className="setup-defaults"><dt>Session time cap</dt><dd>{defaults?defaults.caps?.maxMinutes?`${defaults.caps.maxMinutes} minutes`:'Not set':'Could not load settings'}</dd><dt>Token cap</dt><dd>{defaults?defaults.caps?.maxTokens?.toLocaleString()??'Not set':'Unknown'}</dd><dt>Quiet hours</dt><dd>{defaults?defaults.quietHours?.enabled?'Enabled':'Off':'Unknown'}</dd><dt>Library</dt><dd>Live-call archiving is opt-in.</dd></dl><a href="/settings#caps">Review execution limits ↗</a><p>Recorded workflows keep their observed steps, reviewable text, and verified replay statistics. Unsupported actions stay visible as checkpoints.</p></>}
 {step===5&&<><h1>Start with one useful result.</h1><p>Setup saves your preferences. Capability checks keep their own status; finishing this screen does not mark untested actions as working.</p><div className="setup-paths"><button disabled={busy} onClick={()=>void save(5,true,'/learn')}><strong>Learn and practice</strong><small>Build a skill, try an exercise, and get feedback.</small></button><button disabled={busy} onClick={()=>void save(5,true,'/ventures')}><strong>Explore a business idea</strong><small>Start a product or service experiment with evidence.</small></button><button disabled={busy} onClick={()=>void save(5,true,'/activity')}><strong>Teach a workflow</strong><small>Open the notch → Watch me → review → replay.</small></button></div><p>⌘1–⌘6 switch sections. ⌘J opens your assistant.</p></>}
 </>}{error&&<p className="setup-error" role="alert">{error}<button onClick={()=>{setProfile(null);reload(n=>n+1);}} disabled={busy}>Reload saved setup</button></p>}</fieldset><footer className="wel-foot"><span>{busy?'Saving…':profile?'Progress saves when you continue.':'Your content and connections stay intact.'}</span>{profile&&step<5&&<button className="wel-next" disabled={busy} onClick={()=>void save(step+1)}>Save & continue <ArrowRight size={14}/></button>}</footer></div></div>;
}
function Perm({icon:Icon,title,why,on,onAsk}:{icon:typeof Mic;title:string;why:string;on?:boolean;onAsk:()=>void}){return <div className="wel-item"><Icon size={18}/><div><b>{title}</b><small>{why}</small></div>{on?<span><Check size={13}/>Granted</span>:<button onClick={onAsk}>{on===false?'Review permission':'Check / allow'}</button>}</div>;}
